# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EVObPpghxkeJ1zR7Mr31EZguXrLhFUTK
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar el dataset de Spotify y limpiar nombres de columnas
df = pd.read_csv("spotifydataset.csv")
df.columns = df.columns.str.strip()  # Eliminar espacios en los nombres de columna

# Seleccionar las 10 canciones más populares
df_sorted = df.sort_values(by="track_popularity", ascending=False).head(10)

# Mejorar el diseño del gráfico
sns.set_style("darkgrid")
plt.figure(figsize=(12, 6))
colores = sns.color_palette("coolwarm", len(df_sorted))  # Colores vibrantes

plt.barh(df_sorted["track_name"], df_sorted["track_popularity"], color=colores, edgecolor="black")

# Ajustes de diseño
plt.xlabel("Popularidad", fontsize=12, fontweight="bold")
plt.ylabel("Canción", fontsize=12, fontweight="bold")
plt.title("🎶 Top 10 Canciones por Popularidad en Spotify 🎶", fontsize=14, fontweight="bold")
plt.gca().invert_yaxis()  # Invertir el orden para mejor lectura

# Guardar y mostrar el gráfico
plt.show()